### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by EhsanTgv** [includeamin/ChiChiApp_Docs#2]
# URL
checkout/delivery/prices/
checkout/submit/userinfo
checkout/submit/userinfo
checkout/packageinfo/

# PORT
30034

# Error Description
"State": false, "Description": ["type object 'Checkout' has no attribute 'get_price_for_delivery'"
"State": false, "Description": ["type object 'Checkout' has no attribute 'submit_user_info'"]
"State": false, "Description": ["type object 'Checkout' has no attribute 'get_package_info'"]

# other data that can help

**Comment by includeamin** [comment]
@EhsanTgv salam ehsan ino lotfan check kon fekr konm ok shode
